import './event/eventController.js'
import './home/homeController.js'
import './login/loginController.js'
import './register/registerController.js'
import './universityRegister/universityRegisterController.js'
