import './event/directives/index.js'
import './dashboard/dashboardController.js'
import './event/eventController.js'
import './home/homeController.js'
import './login/loginController.js'
import './university/universityController.js'
